Non-existent names now return nxdomain.  Fixed a typo.

diff --git a/ansible/roles/dns_external/files/bin/dns_root_agent b/ansible/roles/dns_external/files/bin/dns_root_agent
--- a/ansible/roles/dns_external/files/bin/dns_root_agent
+++ b/ansible/roles/dns_external/files/bin/dns_root_agent
@@ -25,20 +25,23 @@ if ! grep -qF ' neuronpointer.net' /etc/hosts; then
   || fail $err_append 'Failed to append a line to /etc/hosts.'
 fi
 
-if ! grep -qF "${neuronpointer_ip} neuronpointer.net" /etc/hosts; then
+# The list of externally visible subdomains should come from ansible
+# inventory, instead of being written explicitly here, in code.
+line="${neuronpointer_ip}"' neuronpointer\.net remote\.neuronpointer\.net nagios\.neuronpointer\.net'
+if ! grep -qF "${line} neuronpointer.net" /etc/hosts; then
   sed -i -E \
-    's/.* neuronpointer\.net.*$/'$neuronpointer_ip' neuronpointer\.net remote\.neuronpointer\.net nagios\.neuronponter\.net/' \
+    's/.* neuronpointer\.net.*$/'"${line}"'/' \
     /etc/hosts \
   || fail $err_sed_hosts "sed failed:  ${?}"
   service dnsmasq force-reload \
   || fail $err_service_reload "service reload failed:  ${?}"
 fi
 
-if ! grep -qF "address=/.neuronpointer.net/neuronpointer.net/${neuronpointer_ip}" /etc/dnsmasq.conf; then
-  sed -i -E \
-    's/^address=\/.neuronpointer\.net\/neuronpointer\.net\/[0-9.]*$/address=\/.neuronpointer.net\/neuronpointer.net\/'$neuronpointer_ip'/' \
-    /etc/dnsmasq.conf \
-  || fail $err_sed_conf "sed failed:  ${?}"
-  service dnsmasq restart \
-  || fail $err_service_restart "service restart failed:  ${?}"
-fi
+#if ! grep -qF "address=/.neuronpointer.net/neuronpointer.net/${neuronpointer_ip}" /etc/dnsmasq.conf; then
+#  sed -i -E \
+#    's/^address=\/.neuronpointer\.net\/neuronpointer\.net\/[0-9.]*$/address=\/.neuronpointer.net\/neuronpointer.net\/'$neuronpointer_ip'/' \
+#    /etc/dnsmasq.conf \
+#  || fail $err_sed_conf "sed failed:  ${?}"
+#  service dnsmasq restart \
+#  || fail $err_service_restart "service restart failed:  ${?}"
+#fi
