initialize_file now reports whether or not it made a change.

diff --git a/ansible/files/scripts/initialize_file b/ansible/files/scripts/initialize_file
--- a/ansible/files/scripts/initialize_file
+++ b/ansible/files/scripts/initialize_file
@@ -5,12 +5,29 @@ owner=$2
 group=$3
 mode=$4
 
+changed=''
+
 fail() {
   echo -e "ERROR:  ${2}" >&2
   exit $1
 }
 
-touch $file || fail 1 "touch failed"
-chown "${owner}:${group}" "${file}" || fail 2 "chown failed"
-chmod "${mode}" "${file}" || fail 3 "chmod failed"
+if ! test -e $file; then
+  touch $file || fail 1 "touch failed"
+  changed='changed'
+fi
 
+if ! (
+     test "${owner}" = "$(stat -c %U $file)" \
+  && test "${group}" = "$(stat -c %G $file)"
+); then
+  chown "${owner}:${group}" "${file}" || fail 2 "chown failed"
+  changed='changed'
+fi
+
+if ! test "${mode}" = "$( printf "%04d\n" $(stat -c %a $file) )"; then
+  chmod "${mode}" "${file}" || fail 3 "chmod failed"
+  changed='changed'
+fi
+
+echo $changed
