The monitoring agent is working.  The service checks being built around it are working.  I know whether the agent is running.  I know whether my pictures have been synced from my phone.  I decided to hide the minimially populated host_templates and service_templates directories under just plain templates/.  I removed a servicedependency block that nagios was complaining about from a lot of services.  It was being ignored.

diff --git a/ansible/roles/nagios/files/bin/agent_command b/ansible/roles/nagios/files/bin/agent_command
--- a/ansible/roles/nagios/files/bin/agent_command
+++ b/ansible/roles/nagios/files/bin/agent_command
@@ -1,17 +1,24 @@
 #!/bin/bash
 
-if ! test 2 == "${#}"; then
-  echo 'Wrong number of arguments.  Specify host and agent command.' >&2
+
+function fail {
+  echo -e "Error:  ${1}" >&2
   exit 1
+}
+
+if ! test 2 == "${#}"; then
+  fail 'Wrong number of arguments.  Specify host and agent command.'
 fi
 
-agent_in="${HOME}/agent_in"
-agent_out="${HOME}/agent_out"
+agent_in="/tmp/agent_in"
+agent_out="/tmp/agent_out"
 
 rm -f "${agent_in}"
 mkfifo "${agent_in}"
+chmod 0600 "${agent_in}"
 rm -f "${agent_out}"
 mkfifo "${agent_out}"
+chmod 0600 "${agent_out}"
 
 ssh \
   "${1}" \
diff --git a/ansible/roles/nagios/files/bin/check_rsync_timestamp b/ansible/roles/nagios/files/bin/check_rsync_timestamp
--- a/ansible/roles/nagios/files/bin/check_rsync_timestamp
+++ b/ansible/roles/nagios/files/bin/check_rsync_timestamp
@@ -1,6 +1,22 @@
 #!/bin/bash
 
-timestamp="$(/usr/local/bin/agent_command "${1}" rsync_timestamp)"
+timestamp="$(
+  /usr/local/bin/agent_command "${1}" rsync_timestamp 2>&1
+)" 
+agent_command_ret="${?}"
+
+if test '' == "${timestamp}"; then
+  echo "No recent log entries."
+  exit 2
+fi
+
+if ! test 0 == "${agent_command_ret}"; then 
+  echo "Error:  agent_command returned:  ${agent_command_ret}"
+  echo "Host address:  ${1}"
+  echo "Output:  ${timestamp}"
+  exit 2
+fi
+
 timestamp_hr="$(date -d "@${timestamp}")"
 now="$(date +%s)"
 delta="$(( ${now} - ${timestamp} ))"
