Improved dependency handling.  Templated ca conf's.  Domain is now templated.  Needs testing.

diff --git a/ssl/generate b/ssl/generate
--- a/ssl/generate
+++ b/ssl/generate
@@ -61,6 +61,25 @@ else
   inform "Directory exists:  ${ca_root_sensitive_dir}"
 fi
 
+if newer_than_deps "${ca_root_conf_template}" "${depend_on_ca_root_conf_template[@]}"; then
+  remove_stale "${depend_on_ca_root_conf_template[@]}"
+fi
+
+if ! test -e "${ca_root_conf}"; then
+  cp "${ca_root_conf_template}" "${ca_root_conf}" \
+  || fail $ERR_CONF "Failed to create conf:  ${ca_root_conf}"
+
+  sed -i 's/DOMAIN/'${domain}'/' "${ca_root_conf}" \
+  || fail $ERR_CONF "Failed to inject domain name:  ${domain}"
+  inform "Injected domain name:  ${1}"
+else
+  inform "Conf exists:  ${ca_root_conf}"
+fi
+
+if newer_than_deps "${ca_root_conf}" "${depend_on_ca_root_conf[@]}"; then
+  remove_stale "${depend_on_ca_root_conf[@]}"
+fi
+
 if ! test -e "${ca_root_key}"; then
   rm -f "${ca_root_dir}/index.txt"{,.attr} \
   || fail $ERR_GENRSA "Failed to remove stale index files."
@@ -147,6 +166,25 @@ else
   inform "Directory exists:  ${ca_intermediate_sensitive_dir}"
 fi
 
+if newer_than_deps "${ca_intermediate_conf_template}" "${depend_on_ca_intermediate_conf_template[@]}"; then
+  remove_stale "${depend_on_ca_intermediate_conf_template[@]}"
+fi
+
+if ! test -e "${ca_intermediate_conf}"; then
+  cp "${ca_intermediate_conf_template}" "${ca_intermediate_conf}" \
+  || fail $ERR_CONF "Failed to create conf:  ${ca_intermediate_conf}"
+
+  sed -i 's/DOMAIN/'${domain}'/' "${ca_intermediate_conf}" \
+  || fail $ERR_CONF "Failed to inject domain name:  ${domain}"
+  inform "Injected domain name:  ${1}"
+else
+  inform "Conf exists:  ${ca_intermediate_conf}"
+fi
+
+if newer_than_deps "${ca_intermediate_conf}" "${depend_on_ca_intermediate_conf[@]}"; then
+  remove_stale "${depend_on_ca_intermediate_conf[@]}"
+fi
+
 if ! test -e "${ca_intermediate_key}"; then
   rm -f "${ca_intermediate_dir}/index.txt"{,.attr} \
   || fail $ERR_GENRSA "Failed to remove stale index files."
@@ -222,13 +260,22 @@ if ! test 'yes' = "${ca_only}"; then
     inform "Directory exists:  ${sensitive_host_dir}"
   fi
 
+  if newer_than_deps "${host_conf_template}" "${depend_on_host_conf_template[@]}"; then
+    remove_stale "${depend_on_host_conf_template[@]}"
+  fi
+
   if ! test -e "${host_conf}"; then
     cp "${host_conf_template}" "${host_conf}" \
     || fail $ERR_CONF "Failed to create conf:  ${host_conf}"
 
+    sed -i 's/DOMAIN/'${domain}'/' "${host_conf}" \
+    || fail $ERR_CONF "Failed to inject domain name:  ${domain}"
+    inform "Injected domain name:  ${1}"
+
     sed -i 's/COMMONNAME/'${1}'/' "${host_conf}" \
     || fail $ERR_CONF "Failed to inject common name:  ${1}"
     inform "Injected common name:  ${1}"
+
     n=1
     for shortname in "${@}"; do
       if echo "${shortname}" | grep -q '\.'; then
