DNS updates should finally be working again.

diff --git a/playbooks/roles/dns2/files/bin/dns_root_agent b/playbooks/roles/dns2/files/bin/dns_root_agent
--- a/playbooks/roles/dns2/files/bin/dns_root_agent
+++ b/playbooks/roles/dns2/files/bin/dns_root_agent
@@ -4,23 +4,41 @@ read neuronpointer_ip < /etc/neuronpointer.net
 
 ip_regex='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
 
-if echo neuronpointer_ip | grep -qE $ip_regex; then
-  if ! grep -qF ' neuronpointer.net' /etc/hosts; then
-    echo ' neuronpointer.net' >> /etc/hosts
-  fi
+fail() {
+  echo "Error:  ${2}" >&2
+  exit $1
+}
 
-  ! grep -qF "${neuronpointer_ip} neuronpointer.net" /etc/hosts \
-  && sed \
-    -i -E \
-    's/.* neuronpointer\.net$/'$neuronpointer_ip' neuronpointer\.net/' \
-    /etc/hosts \
-  && service dnsmasq force-reload
+err_invalid=1
+err_append=2
+err_sed_hosts=3
+err_service_reload=4
+err_sed_conf=5
+err_service_restart=6
 
-  ! grep -qF "address=/.neuronpointer.net/neuronpointer.net/${neuronpointer_ip}" /etc/dnsmasq.conf \
-  && sed \
-    -i -E \
-    's/^address=\/.neuronpointer\.net\/neuronpointer\.net\/[0-9.]*$/address=\/.neuronpointer.net\/neuronpointer.net\/'$neuronpointer_ip'/' \
-    /etc/dnsmasq.conf \
-  && service dnsmasq restart
+if ! echo $neuronpointer_ip | grep -qE $ip_regex; then
+  fail $err_invalid "Invalid IP address:  ${neuronpointer_ip}"
 fi
 
+if ! grep -qF ' neuronpointer.net' /etc/hosts; then
+  echo ' neuronpointer.net' >> /etc/hosts \
+  || fail $err_append 'Failed to append a line to /etc/hosts.'
+fi
+
+if ! grep -qF "${neuronpointer_ip} neuronpointer.net" /etc/hosts; then
+  sed -i -E \
+    's/.* neuronpointer\.net$/'$neuronpointer_ip' neuronpointer\.net/' \
+    /etc/hosts \
+  || fail $err_sed_hosts "sed failed:  ${?}"
+  service dnsmasq force-reload \
+  || fail $err_service_reload "service reload failed:  ${?}"
+fi
+
+if ! grep -qF "address=/.neuronpointer.net/neuronpointer.net/${neuronpointer_ip}" /etc/dnsmasq.conf; then
+  sed -i -E \
+    's/^address=\/.neuronpointer\.net\/neuronpointer\.net\/[0-9.]*$/address=\/.neuronpointer.net\/neuronpointer.net\/'$neuronpointer_ip'/' \
+    /etc/dnsmasq.conf \
+  || fail $err_sed_conf "sed failed:  ${?}"
+  service dnsmasq restart \
+  || fail $err_service_restart "service restart failed:  ${?}"
+fi
