Renamed and enabled the first agent module.  Fixed some messy session end-of-session handling in agent_shell.  Made socat failures recoverable in agent.

diff --git a/ansible/roles/monitored/files/bin/agent b/ansible/roles/monitored/files/bin/agent
--- a/ansible/roles/monitored/files/bin/agent
+++ b/ansible/roles/monitored/files/bin/agent
@@ -16,6 +16,11 @@ function fail {
 }
 
 
+function warn {
+  echo -e "Warning:  ${1}" >&2
+}
+
+
 mkdir -p "${socket_dir}" \
   || fail "Failed to create socket directory:  ${socket_dir}"
 
@@ -31,7 +36,7 @@ rm -f "${socket}" \
 while sleep 1; do
   echo "Launching socat and agent_shell."
   socat UNIX-LISTEN:"${socket}",user="${user}",group="${group}",mode="${socket_mode}", EXEC:"${agent_shell}" \
-    || fail "Failed to launch socat."
+    || warn "Failed to launch socat."
   echo "socat returned success."
 done
 
